### ISSUE TITLE
Run build_compiler_rt.sh

### ISSUE THREAD

**Issue by iamkhalidbashir** [crazy-max/docker-osxcross#25]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-osxcross/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Solves https://github.com/tpoechtrager/osxcross/issues/278

### Expected behaviour

Solves https://github.com/tpoechtrager/osxcross/issues/278

### Actual behaviour

Solves https://github.com/tpoechtrager/osxcross/issues/278

### Steps to reproduce

Solves https://github.com/tpoechtrager/osxcross/issues/278

### Docker info

```yaml
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 22
  Running: 20
  Paused: 0
  Stopped: 2
 Images: 386
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: sysbox-runc io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-73-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 31.29GiB
 Name: KHALID-BASHIR
 ID: OFEW:TE2V:PHIA:GWYX:UIL4:XNPX:4MJO:2UNJ:6YCA:PPBJ:CIFJ:JAXI
 Docker Root Dir: /mnt/Work/system/docker
 Debug Mode: false
 Username: amoxt
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.25.0.0/16, Size: 24
```

### Version

* MacOSX SDK version:
* System info (type `uname -a`):

### Container logs

Solves https://github.com/tpoechtrager/osxcross/issues/278
