### ISSUE TITLE
Alpine Example Slight Adjustment

### ISSUE THREAD

**Issue by coderforlife** [crazy-max/docker-osxcross#26]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-osxcross/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The `fts` apk should be added in the Alpine example, it is needed by some of the osxcross binaries (at least `*-ar`, possibly others; the `*-ar` binary is required for cross-compiling with meson). It is also a very small install (28 kb install size).

### Expected behaviour

The alpine dockerfile example to be able to run the `*-ar` binaries.

### Actual behaviour

Error message when running those binaries, for example:

`Error loading shared library libfts.so.0: No such file or directory (needed by /osxcross/bin/x86_64-apple-darwin22.2-ar)`

### Steps to reproduce

Run `x86_64-apple-darwin22.2-ar` in the docker container example (instead of o64-...).

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 44
 Server Version: 20.10.21
 Storage Driver: btrfs
  Build Version: Btrfs v6.0.2
  Library Version: 102
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
  selinux
  cgroupns
 Kernel Version: 6.2.15-100.fc36.x86_64
 Operating System: Fedora Linux 36 (Cinnamon)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 250.5GiB
 Name: hippocampus.cslab.moravian.edu
 ID: RSQ4:NTHI:7ZCF:S37J:37GJ:EXGI:I5J5:GGY3:TZ6I:2IE7:OLDM:4NB7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

### Version

* MacOSX SDK version: latest
* System info (type `uname -a`): really?

### Container logs

Simple suggestion doesn't need all of this.
